apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-api-worker
  namespace: asr-api
spec:
  template:
    spec:
      containers:
        - name: worker
          image: asr-registry.wavey.ai/asr-api-worker:trt-main
          startupProbe:
            failureThreshold: 120
          volumeMounts:
            - name: trt-cache
              mountPath: /var/cache/asr-api-trt
      volumes:
        - name: trt-cache
          emptyDir: {}
