apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-api-ingress
  namespace: asr-api
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - asr.wavey.ai
      secretName: asr-wavey-ai-tls
  rules:
    - host: asr.wavey.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asr-api-ingress
                port:
                  number: 8443
