apiVersion: v1
kind: Service
metadata:
  name: asr-api-ingress
  namespace: asr-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: asr-api-ingress
  ports:
    - name: https
      port: 8443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: asr-api-ingress-internal
  namespace: asr-api
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: asr-api-ingress
  ports:
    - name: https
      port: 8443
      targetPort: https
