apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-api-ingress
  namespace: asr-api
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - asr.wavey.ai
      secretName: asr-wavey-ai-tls
  rules:
    - host: asr.wavey.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asr-api-ingress
                port:
                  number: 8443
