apiVersion: v1
kind: Service
metadata:
  name: transcriber-ingress
  namespace: transcriber
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: transcriber-ingress
  ports:
    - name: https
      port: 8443
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: transcriber-ingress-internal
  namespace: transcriber
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: transcriber-ingress
  ports:
    - name: https
      port: 8443
      targetPort: https
